trigger:
  branches:
    include:
      - main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Building the app..."
    - script: echo "Build completed."

- stage: Test
  dependsOn: Build
  jobs:
  - job: RunTests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Running unit tests..."
    - script: exit 1  # simulate test failure (remove in real setup)

- stage: Deploy
  dependsOn: Test
  condition: succeeded()   # ensures deploy runs only if tests succeed
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deploying application..."
